env:
  browser: true
  commonjs: true
  node: true
extends:
  - google
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
  requireConfigFile: false
rules:

  max-len:
    - warn
    - code: 120

  valid-jsdoc:
    - warn

  new-cap:
    - error
    - capIsNewExceptions:
        - Trait
