env:
  node: true
extends:
  - google
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
rules:

  max-len:
    - warn
    - code: 120

  valid-jsdoc:
    - off

  new-cap:
    - error
    - capIsNewExceptions:
        - Trait

  no-unused-vars:
    - off

  "@typescript-eslint/no-unused-vars":
    - error
